---
  - name: "My first play"
    hosts: localhost

    tasks:

      #- name: "test reachability"
      #  ping:

      - name: "file details"
        find:
          paths: ~/Ansible/LinkedInLearning/LearningAnsible
      #    patterns: "*.txt"
          file_type: file
      #  register: output

      #- debug: var=item.path
      #  with_items: "{{ output.files }}"