---
  - name: "Retrieve the API Key for the current user {{ ansible_ssh_user }}"
    uri:
      url: "https://{{ ansible_host }}/api/?type=keygen&user={{ ansible_ssh_user }}&password={{ ansible_ssh_pass }}"
      method: POST
      body_format: json
      return_content: yes
      follow_redirects: all
      validate_certs: no
    register: panw_response
    # delegate_to: localhost

  # - debug:
  #     msg: "{{ panw_response.content | from_json | json_query('key') }}"

  - xml:
      xmlstring: "{{ panw_response.content }}"
      xpath: "/response/result/key"
      content: "text"
    register: api_key

  # - debug:
  #     msg: "{{ api_key }}"  

  - name: Add API Key to Provider
    set_fact:
      providerAPI:
        api_key: "{{ api_key.matches[0].key }}"
        ip_address: "{{ ansible_host }}"
        password: "{{ ansible_ssh_pass }}"
        username: "{{ ansible_ssh_user }}"

  # - debug:
  #     msg: "{{ providerVARS }}"  

  # - debug:
  #     msg: "{{ providerAPI }}"  


  # - name: Get the system info
  #   paloaltonetworks.panos.panos_op:
  #     provider: '{{ providerVARS }}'
  #     cmd: 'show system info'
  #   register: res

  # - debug:
  #     msg: '{{ res.stdout }}'

  # # Gather facts
  # - name: Get facts
  #   paloaltonetworks.panos.panos_facts:
  #     provider: "{{ providerAPI }}"
  #     #gather_subset: ['config']
